### PR TITLE
Dependency update

### PR DESCRIPTION
**Pull request by jongbonga**

### CODE REVIEW

**Review by PiDelport — COMMENTED** [review]
We should probably keep the caret / `^` specifiers in the dependencies?

**Comment by jongbonga** [comment]
> We should keep the caret / `^` specifiers in the dependencies?

I think the tilde (~) is safer, weird stuff sometimes happens on minor version updates.
But I want to know why you'd prefer the caret (^)

**Comment by PiDelport** [comment]
Oh, the `~` modifier is fine too, yeah! As long as we have some kind of range constraint in the `package.json` to facilitate periodic updates, rather than hard-pinning things to specific patch versions there.

**Comment by jongbonga** [comment]
The vue-cli(s) have the `~` and some have `^`.
Are there specific packages you would like to amend version?

**Comment by PiDelport** [comment]
Well, we should probably just keep the `^` (or switch to `~`) for all the dependencies that had them before, rather than removing them in this PR?

**Review by PiDelport — APPROVED** [review]
Coolness, looks good!

**Pull request merged**
